### ISSUE TITLE
Change the first day of the week from Sunday to Monday

### ISSUE THREAD

**Issue by asapbox** [GaspardMerten/date_range_picker#9]
Could not find in the documentation if there is an option to provide Locale to change the first day of the week from Sunday to Monday.

**Comment by mauriziopinotti** [comment]
@asapbox I've pushed a PR to add the option: https://github.com/GaspardMerten/date_range_picker/pull/15

```dart
DateRangePickerWidget(
    ...
    firstDayOfWeek: 1, // Monday
);
```

While it's being merged you can use my fork adding the override in pubspec.yaml:

```yaml
dependency_overrides:
  flutter_date_range_picker:
    git: https://github.com/easyhour/date_range_picker.git
```
